language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-23.0.2

    - android-23

    # Additional components
    - extra-android-m2repository
    - extra-android-support

before_script:
    ## We need to be able to test the compile.
    sed -ie 's%Get_your_own_key_ugh%0%g' MPDroid/src/crashlytics/AndroidManifest.xml

# This project doesn't support checkConnected, which is
#  the default script label for the Android plugin.
script:
    ## Build /everything/ but MPDroid Javadoc (Android Support Libraries break the TravisCI build).
    ## It's not fast, but it's thorough.
    ./gradlew build JMPDCommAndroid:debugJavadoc JMPDCommJava:javadoc
