language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-23.0.1
    - doc-23

    - android-23

    # Additional components
    - extra-android-m2repository
    - extra-android-support

before_script:
    ## We need to be able to test the compile.
    sed -ie 's%Get_your_own_key_ugh%0%g' MPDroid/src/crashlytics/AndroidManifest.xml

# This project doesn't support checkConnected, which is
#  the default script label for the Android plugin.
script:
    ## Build the standard MPDroid distribution and check to
    ### make sure the plain Java build didn't break.

    ./gradlew assembleCrashlytics assembleFoss assembleLeakCanary JMPDCommAndroid:debugJavadoc JMPDCommAndroid:test JMPDCommJava:Build JMPDCommJava:javadoc JMPDCommJava:test
